name: wave_sla
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'


environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  path: ^1.8.3
  wave_sdk:
   path: ../wave_sdk

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
